#Makefile for ClassC/Elaine

# NOTES:
# 1) The default make target (ceparser) will make files for the AT&T Unix PC
#	This uses the shared library.  Note that the variable argument print
#	routine "vfprintf" is not included in the AT&T 3.51 release of
#	its shared library, so the local library "libvp.a" must be created
#	with the object code for the "vfprintf" routine extracted from
#	the standard libraries.
#		A simpler alternative is selecting target "unshared";
#	which should
#	compile on all Sys V machines.  UCB systems will require some
#	conversion of source files.
#
# 2) This makefile puts "ceparser" and "ce" into /usr/local/bin and
#	"libce.o" and "libceO.o" into /usr/local/lib.  Change this
#	if it is unsuitable.


# LBS= -ly -ll -lg 
#CFLAGS = -DDBG -g -DATT
CFLAGS =  -DSUN -O
LBS= -ll -lg
XLBS= -ll



ClassC:	ceparser libce.o

ceparser:	y.tab.o lex.yy.o parse.o funcs3.o funcs2.o funcs1.o libce.o
	echo "Make sure you built this with BUILD ..."
	cc ${CFLAGS} parse.o y.tab.o lex.yy.o funcs3.o funcs2.o funcs1.o ${XLBS} -o ceparser

sharedlib:	y.tab.o lex.yy.o parse.o funcs1.o funcs3.o funcs2.o
	ld parse.o y.tab.o lex.yy.o funcs3.o funcs2.o funcs1.o ${LBS} -o ceparser
	ld parse.o funcs1.o ${LBS} -o ceparser
y.tab.o:	y.tab.c common.h
	cc ${CFLAGS} -c y.tab.c $(SWITCH)
		
lex.yy.o:	lex.yy.c  common.h

lex.yy.c:	r.l
	lex r.l  

y.tab.c:	ce.y 
	yacc -d ce.y

libce.o:	libce.c
	cc ${CFLAGS} -cg -DDEBUG libce.c
#	cp libce.o ../bin/libceDB.o
	mv libce.o libceDB.o
	cc ${CFLAGS} -cO libce.c
#	cp libce.o ../bin
